### DISCUSSION TITLE
Install js import glob plugin: esbuild-plugin-import-glob

### DISCUSSION THREAD

**Discussion by mhsdesign** [CarbonPackages/Carbon.Pipeline#20] [Q&A]
Hi ;)

i cant get this eslint plugin to work. https://github.com/thomaschaaf/esbuild-plugin-import-glob

```
Error: Build failed with 1 error:
DistributionPackages/MI.Site/Resources/Private/Fusion/Alpine.js:17:8: ERROR: Could not resolve "./Component/**/*"
```

i installed the plugin and activated it in: pipeline.yaml
```
esbuild:
  additionalPlugins:
    esbuild-plugin-import-glob: true
```

the above plugin should allow something like this this which would be really cool ^^:
```js
import AlpineComponents from './Component/**/*.alphine.js';
AlpineComponents.map(component, component => {
    component.default(Alpine)
})
```

**Comment by jonnitto** [comment]
Did you also tried this:

```yaml
esbuild:
  additionalPlugins:
    esbuild-plugin-import-glob:
      functionName: setup
```

**Comment by mhsdesign** [comment]
Hmm no didnt do it, since its a default export https://github.com/thomaschaaf/esbuild-plugin-import-glob/blob/d13aa20635b219a944e811938ff29d42b1238b95/src/index.ts#L48

i also tried

```yaml
esbuild:
  additionalPlugins:
    some-not-installed-plugin: true
```

which raises an exception - so the plugin `esbuild-plugin-import-glob` is installed correctly and recognized by the pipeline https://github.com/CarbonPackages/Carbon.Pipeline/blob/1205f3ac5e866be319861a783ae127bda46e8ca7/Lib/esbuildHelper.mjs#L86
